#!/usr/bin/env bash
set -e

OUTPUT=$(solana program deploy \
  --url http://localhost:8899 \
  --keypair accounts/account1.json \
  target/deploy/laurelin.so)

echo "$OUTPUT"

PROGRAM_ID=$(echo "$OUTPUT" | awk '/Program Id:/ {print $3}')
echo "PROGRAM_ID=$PROGRAM_ID" > gnark-circuit/local.env
echo "Wrote gnark-circuit/local.env"
