#!/bin/bash

#    laurelin-wallet --config ~/.laurelin/$i/config.json --wallet ~/.laurelin/$i/wallet.json pubkey | grep Solana | awk '{print $3}'

laurelin() {
    j=$1
    shift
    laurelin-wallet --config ~/.laurelin/$j/config.json --wallet ~/.laurelin/$j/wallet.json $@
}

if [ "$1" = 'bn254' ]; then
    laurelin 1 pubkey | grep BN254 | awk '{print $4}'
    exit
fi

for ((i=1; i<=$1; i++)); do
    echo "run iteration $i"
    rm -rf  ~/.laurelin/$i
    laurelin $i init --insecure
    laurelin $i config set-program 4eesfezqbNcYSJLmQqvxN38CdsccYGFYUaZdBgQp7a2L
    laurelin $i config set-pk-dir /Users/axoloki/src/laurelin/circuit/setup

    export pubkey=`laurelin $i pubkey | grep Solana | awk '{print $3}'`
    echo "Solana pubkey is $pubkey"
    solana airdrop 100 "$pubkey" --url localhost

    laurelin $i create-account
done
