// setup runs Groth16 trusted setup for TransferCircuit, saves the proving key
// to circuit/setup/pk.bin, and prints the verification key as Rust source
// ready to paste into src/lib.rs.
//
// Usage:
//
//	cd circuit && go run ./setup
package main

import (
	"fmt"
	"math/big"
	"os"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark-crypto/ecc/bn254"
	"github.com/consensys/gnark-crypto/ecc/bn254/fp"
	"github.com/consensys/gnark/backend/groth16"
	groth16bn254 "github.com/consensys/gnark/backend/groth16/bn254"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
	"laurelin/circuit"
)

const pkPath = "setup/pk.bin"

func main() {
	fmt.Fprintln(os.Stderr, "Compiling circuit…")
	ccs, err := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &circuit.RingTransferCircuit{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "compile: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Constraints: %d\n", ccs.GetNbConstraints())

	fmt.Fprintln(os.Stderr, "Running setup…")
	pk, vk, err := groth16.Setup(ccs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "setup: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Writing proving key to %s…\n", pkPath)
	pkFile, err := os.Create(pkPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create pk: %v\n", err)
		os.Exit(1)
	}
	if _, err := pk.WriteTo(pkFile); err != nil {
		fmt.Fprintf(os.Stderr, "write pk: %v\n", err)
		os.Exit(1)
	}
	pkFile.Close()

	vkBN := vk.(*groth16bn254.VerifyingKey)

	fmt.Println("// Auto-generated by `go run ./setup`")
	fmt.Println("// Paste into src/lib.rs, replacing DUMMY_VK.")
	fmt.Println()
	fmt.Println("static REAL_VK: VerificationKey = VerificationKey {")

	fmt.Print("    alpha: ")
	printG1(&vkBN.G1.Alpha)
	fmt.Println(",")

	fmt.Print("    beta:  ")
	printG2(&vkBN.G2.Beta)
	fmt.Println(",")

	fmt.Print("    gamma: ")
	printG2(&vkBN.G2.Gamma)
	fmt.Println(",")

	fmt.Print("    delta: ")
	printG2(&vkBN.G2.Delta)
	fmt.Println(",")

	fmt.Println("    ic: &[")
	for _, p := range vkBN.G1.K {
		fmt.Print("        ")
		p := p // copy for pointer
		printG1(&p)
		fmt.Println(",")
	}
	fmt.Println("    ],")
	fmt.Println("};")
}

// ── serialisation ─────────────────────────────────────────────────────────────

func fpBE(x *fp.Element) [32]byte {
	var bi big.Int
	x.BigInt(&bi)
	var out [32]byte
	bi.FillBytes(out[:])
	return out
}

func g1Bytes(p *bn254.G1Affine) [64]byte {
	var out [64]byte
	x := fpBE(&p.X)
	y := fpBE(&p.Y)
	copy(out[:32], x[:])
	copy(out[32:], y[:])
	return out
}

// g2Bytes encodes a G2 point in EIP-197 format: x_c1 || x_c0 || y_c1 || y_c0
// (imaginary component first — required by Solana alt_bn128_pairing syscall)
func g2Bytes(p *bn254.G2Affine) [128]byte {
	var out [128]byte
	// G2Affine.X and .Y are of type fptower.E2 with exported fields A0 (c0) and A1 (c1)
	xc0 := fpBE(&p.X.A0)
	xc1 := fpBE(&p.X.A1)
	yc0 := fpBE(&p.Y.A0)
	yc1 := fpBE(&p.Y.A1)
	copy(out[0:32],   xc1[:])
	copy(out[32:64],  xc0[:])
	copy(out[64:96],  yc1[:])
	copy(out[96:128], yc0[:])
	return out
}

func printG1(p *bn254.G1Affine) { b := g1Bytes(p); printByteArray(b[:]) }
func printG2(p *bn254.G2Affine) { b := g2Bytes(p); printByteArray(b[:]) }

func printByteArray(b []byte) {
	fmt.Print("[")
	for i, v := range b {
		if i%16 == 0 {
			fmt.Print("\n        ")
		}
		fmt.Printf("0x%02x,", v)
	}
	fmt.Print("\n    ]")
}
