// setup runs Groth16 trusted setup for one or both circuits, saves proving
// keys under circuit/setup/ and writes verification keys as Rust source under src/.
//
// Usage:
//
//	cd circuit && go run ./setup                     # both circuits
//	cd circuit && go run ./setup -circuit transfer   # transfer only
//	cd circuit && go run ./setup -circuit withdraw   # withdraw only
package main

import (
	"flag"
	"fmt"
	"io"
	"math/big"
	"os"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark-crypto/ecc/bn254"
	"github.com/consensys/gnark-crypto/ecc/bn254/fp"
	"github.com/consensys/gnark/backend/groth16"
	groth16bn254 "github.com/consensys/gnark/backend/groth16/bn254"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
	"laurelin/circuit"
)

func main() {
	which := flag.String("circuit", "all", "which circuit to set up: transfer, withdraw, all")
	flag.Parse()

	switch *which {
	case "transfer":
		runSetup("transfer", &circuit.RingTransferCircuit{},
			"setup/transfer_pk.bin", "setup/transfer_vk.bin", "../src/transfer_vk_generated.rs", "TRANSFER_VK")
	case "deposit":
		runSetup("deposit", &circuit.DepositCircuit{},
			"setup/deposit_pk.bin", "setup/deposit_vk.bin", "../src/deposit_vk_generated.rs", "DEPOSIT_VK")
	case "withdraw":
		runSetup("withdraw", &circuit.WithdrawCircuit{},
			"setup/withdraw_pk.bin", "setup/withdraw_vk.bin", "../src/withdraw_vk_generated.rs", "WITHDRAW_VK")
	case "all":
		runSetup("transfer", &circuit.RingTransferCircuit{},
			"setup/transfer_pk.bin", "setup/transfer_vk.bin", "../src/transfer_vk_generated.rs", "TRANSFER_VK")
		runSetup("deposit", &circuit.DepositCircuit{},
			"setup/deposit_pk.bin", "setup/deposit_vk.bin", "../src/deposit_vk_generated.rs", "DEPOSIT_VK")
		runSetup("withdraw", &circuit.WithdrawCircuit{},
			"setup/withdraw_pk.bin", "setup/withdraw_vk.bin", "../src/withdraw_vk_generated.rs", "WITHDRAW_VK")
	default:
		fmt.Fprintf(os.Stderr, "unknown -circuit %q; choose transfer, deposit, withdraw, or all\n", *which)
		os.Exit(1)
	}
}

func runSetup(name string, c frontend.Circuit, pkPath, vkBinPath, vkPath, rustVarName string) {
	fmt.Fprintf(os.Stderr, "=== %s ===\n", name)
	fmt.Fprintln(os.Stderr, "Compiling circuit…")
	ccs, err := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "compile: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Constraints: %d\n", ccs.GetNbConstraints())

	fmt.Fprintln(os.Stderr, "Running setup…")
	pk, vk, err := groth16.Setup(ccs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "setup: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Writing proving key to %s…\n", pkPath)
	pkFile, err := os.Create(pkPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create pk: %v\n", err)
		os.Exit(1)
	}
	if _, err := pk.WriteTo(pkFile); err != nil {
		fmt.Fprintf(os.Stderr, "write pk: %v\n", err)
		os.Exit(1)
	}
	pkFile.Close()

	fmt.Fprintf(os.Stderr, "Writing binary verification key to %s…\n", vkBinPath)
	vkBinFile, err := os.Create(vkBinPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create vk bin: %v\n", err)
		os.Exit(1)
	}
	if _, err := vk.WriteTo(vkBinFile); err != nil {
		fmt.Fprintf(os.Stderr, "write vk bin: %v\n", err)
		os.Exit(1)
	}
	vkBinFile.Close()

	fmt.Fprintf(os.Stderr, "Writing verification key to %s…\n", vkPath)
	vkFile, err := os.Create(vkPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create vk: %v\n", err)
		os.Exit(1)
	}
	writeVK(vkFile, vk, rustVarName)
	vkFile.Close()

	fmt.Fprintln(os.Stderr, "Done.")
}

func writeVK(w io.Writer, vk groth16.VerifyingKey, varName string) {
	vkBN := vk.(*groth16bn254.VerifyingKey)

	fmt.Fprintln(w, "// Auto-generated by `cd circuit && go run ./setup` — do not edit.")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "static %s: VerificationKey = VerificationKey {\n", varName)

	fmt.Fprint(w, "    alpha: ")
	fprintG1(w, &vkBN.G1.Alpha)
	fmt.Fprintln(w, ",")

	fmt.Fprint(w, "    beta:  ")
	fprintG2(w, &vkBN.G2.Beta)
	fmt.Fprintln(w, ",")

	fmt.Fprint(w, "    gamma: ")
	fprintG2(w, &vkBN.G2.Gamma)
	fmt.Fprintln(w, ",")

	fmt.Fprint(w, "    delta: ")
	fprintG2(w, &vkBN.G2.Delta)
	fmt.Fprintln(w, ",")

	fmt.Fprintln(w, "    ic: &[")
	for _, p := range vkBN.G1.K {
		fmt.Fprint(w, "        ")
		p := p
		fprintG1(w, &p)
		fmt.Fprintln(w, ",")
	}
	fmt.Fprintln(w, "    ],")
	fmt.Fprintln(w, "};")
}

// ── serialisation ─────────────────────────────────────────────────────────────

func fpBE(x *fp.Element) [32]byte {
	var bi big.Int
	x.BigInt(&bi)
	var out [32]byte
	bi.FillBytes(out[:])
	return out
}

func g1Bytes(p *bn254.G1Affine) [64]byte {
	var out [64]byte
	x := fpBE(&p.X)
	y := fpBE(&p.Y)
	copy(out[:32], x[:])
	copy(out[32:], y[:])
	return out
}

// g2Bytes encodes a G2 point in EIP-197 format: x_c1 || x_c0 || y_c1 || y_c0
// (imaginary component first — required by Solana alt_bn128_pairing syscall)
func g2Bytes(p *bn254.G2Affine) [128]byte {
	var out [128]byte
	xc0 := fpBE(&p.X.A0)
	xc1 := fpBE(&p.X.A1)
	yc0 := fpBE(&p.Y.A0)
	yc1 := fpBE(&p.Y.A1)
	copy(out[0:32],   xc1[:])
	copy(out[32:64],  xc0[:])
	copy(out[64:96],  yc1[:])
	copy(out[96:128], yc0[:])
	return out
}

func fprintG1(w io.Writer, p *bn254.G1Affine) { b := g1Bytes(p); fprintByteArray(w, b[:]) }
func fprintG2(w io.Writer, p *bn254.G2Affine) { b := g2Bytes(p); fprintByteArray(w, b[:]) }

func fprintByteArray(w io.Writer, b []byte) {
	fmt.Fprint(w, "[")
	for i, v := range b {
		if i%16 == 0 {
			fmt.Fprint(w, "\n        ")
		}
		fmt.Fprintf(w, "0x%02x,", v)
	}
	fmt.Fprint(w, "\n    ]")
}
