#![cfg_attr(not(test), no_std)]

#[cfg(not(test))]
extern crate alloc;
#[cfg(not(test))]
use alloc::format;

pub mod bn254;
pub mod groth16;
pub mod instruction;
pub mod state;

use solana_program::{
    account_info::AccountInfo,
    entrypoint::ProgramResult,
    msg,
    program_error::ProgramError,
    pubkey::Pubkey,
    rent::Rent,
    system_instruction,
    program::invoke_signed,
    sysvar::Sysvar,
};

use groth16::{verify, VerificationKey};
use instruction::LaurelinInstruction;
use state::{AccountState, G1Point};

#[cfg(not(test))]
use solana_program::entrypoint;
#[cfg(not(test))]
entrypoint!(process_instruction);

// BN254 G1 generator
pub const G1_X: [u8; 32] = {
    let mut b = [0u8; 32];
    b[31] = 1;
    b
};
pub const G1_Y: [u8; 32] = {
    let mut b = [0u8; 32];
    b[31] = 2;
    b
};
pub const GENERATOR: G1Point = {
    let mut g = [0u8; 64];
    let mut i = 0;
    while i < 32 { g[i] = G1_X[i]; i += 1; }
    let mut i = 0;
    while i < 32 { g[32 + i] = G1_Y[i]; i += 1; }
    g
};

/// Placeholder VK — replace IC/alpha/beta/gamma/delta with real
/// values generated by the circuit trusted setup.
static DUMMY_VK: VerificationKey = VerificationKey {
    alpha: GENERATOR,
    beta:  [0u8; 128],
    gamma: [0u8; 128],
    delta: [0u8; 128],
    ic:    &[GENERATOR],
};

pub fn process_instruction(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    let ix = LaurelinInstruction::try_from_bytes(instruction_data)
        .ok_or(ProgramError::InvalidInstructionData)?;

    match ix {
        LaurelinInstruction::CreateAccount { pubkey, c1, c2 } => {
            process_create_account(program_id, accounts, pubkey, c1, c2)
        }
        LaurelinInstruction::Transfer {
            proof,
            new_sender_c1,
            new_sender_c2,
            new_recv_c1,
            new_recv_c2,
        } => process_transfer(
            program_id,
            accounts,
            proof,
            new_sender_c1,
            new_sender_c2,
            new_recv_c1,
            new_recv_c2,
        ),
        LaurelinInstruction::VerifyProof { proof, public_inputs } => {
            let ok = verify(&DUMMY_VK, &proof, &public_inputs)
                .map_err(|_| ProgramError::InvalidArgument)?;
            if ok {
                msg!("proof verified");
                Ok(())
            } else {
                msg!("proof invalid");
                Err(ProgramError::InvalidArgument)
            }
        }
    }
}

fn process_create_account(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    pubkey: G1Point,
    c1: G1Point,
    c2: G1Point,
) -> ProgramResult {
    if accounts.len() < 3 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let payer = &accounts[0];
    let pda = &accounts[1];
    let system_program = &accounts[2];

    // PDA seed: first 32 bytes of the account's pubkey (the x coordinate)
    let seed = &pubkey[0..32];
    let (expected_pda, bump) =
        Pubkey::find_program_address(&[seed], program_id);

    if pda.key != &expected_pda {
        msg!("PDA mismatch");
        return Err(ProgramError::InvalidArgument);
    }

    let rent = Rent::get()?;
    let lamports = rent.minimum_balance(AccountState::LEN);

    invoke_signed(
        &system_instruction::create_account(
            payer.key,
            pda.key,
            lamports,
            AccountState::LEN as u64,
            program_id,
        ),
        &[payer.clone(), pda.clone(), system_program.clone()],
        &[&[seed, &[bump]]],
    )?;

    let state = AccountState { pubkey, c1, c2 };
    state.write_to(&mut pda.data.borrow_mut());
    Ok(())
}

fn process_transfer(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    proof: state::Groth16Proof,
    new_sender_c1: G1Point,
    new_sender_c2: G1Point,
    new_recv_c1: G1Point,
    new_recv_c2: G1Point,
) -> ProgramResult {
    if accounts.len() < 2 {
        return Err(ProgramError::NotEnoughAccountKeys);
    }
    let sender_pda = &accounts[0];
    let recv_pda = &accounts[1];

    // verify both PDAs are owned by this program
    if sender_pda.owner != program_id || recv_pda.owner != program_id {
        return Err(ProgramError::IncorrectProgramId);
    }

    // load sender state for public inputs
    let sender_state = AccountState::try_from_bytes(&sender_pda.data.borrow())
        .ok_or(ProgramError::InvalidAccountData)?;

    // public inputs: sender_pubkey (2 scalars) || old_C1 (2) || old_C2 (2)
    //                || new_sender_C1 (2) || new_sender_C2 (2)
    //                || new_recv_C1 (2) || new_recv_C2 (2) = 14 scalars
    let public_inputs = build_public_inputs(
        &sender_state,
        &new_sender_c1,
        &new_sender_c2,
        &new_recv_c1,
        &new_recv_c2,
    );

    let ok = verify(&DUMMY_VK, &proof, &public_inputs)
        .map_err(|_| ProgramError::InvalidArgument)?;
    if !ok {
        msg!("balance proof invalid");
        return Err(ProgramError::InvalidArgument);
    }

    // update sender ciphertext
    {
        let mut data = sender_pda.data.borrow_mut();
        data[64..128].copy_from_slice(&new_sender_c1);
        data[128..192].copy_from_slice(&new_sender_c2);
    }

    // update receiver ciphertext homomorphically: add new_recv to existing
    {
        let recv_state = AccountState::try_from_bytes(&recv_pda.data.borrow())
            .ok_or(ProgramError::InvalidAccountData)?;
        let new_c1 = bn254::g1_add(&recv_state.c1, &new_recv_c1)
            .map_err(|_| ProgramError::InvalidArgument)?;
        let new_c2 = bn254::g1_add(&recv_state.c2, &new_recv_c2)
            .map_err(|_| ProgramError::InvalidArgument)?;
        let mut data = recv_pda.data.borrow_mut();
        data[64..128].copy_from_slice(&new_c1);
        data[128..192].copy_from_slice(&new_c2);
    }

    msg!("transfer complete");
    Ok(())
}

/// Encode each G1 point as two 32-byte scalars (x, y) for use as SNARK public inputs
fn build_public_inputs(
    sender: &AccountState,
    new_sender_c1: &G1Point,
    new_sender_c2: &G1Point,
    new_recv_c1: &G1Point,
    new_recv_c2: &G1Point,
) -> alloc::vec::Vec<state::Scalar> {
    let mut inputs = alloc::vec::Vec::with_capacity(14);
    for point in &[
        &sender.pubkey,
        &sender.c1,
        &sender.c2,
        new_sender_c1,
        new_sender_c2,
        new_recv_c1,
        new_recv_c2,
    ] {
        let mut x = [0u8; 32];
        let mut y = [0u8; 32];
        x.copy_from_slice(&point[0..32]);
        y.copy_from_slice(&point[32..64]);
        inputs.push(x);
        inputs.push(y);
    }
    inputs
}
